### ISSUE TITLE
Could not load file or assembly 'NETMapnik.DLL' or one of its dependencies. The specified module could not be found

### ISSUE THREAD

**Issue by Charmatzis** [jbrwn/NET-Mapnik#22] opened 2015-08-27 15:10 UTC
Hi,

I am trying to work with the NETMapnik and so far I have succeeded with an console app. (Great job!)
I tried to do the same and install with a nuget package  in an ASP.NET API project  and and when I run the api site the error is:
"Could not load file or assembly 'NETMapnik.DLL' or one of its dependencies. The specified module could not be found" 
I also found that in the mapnik.x64.props file in packages there were some errors and you need to change it to that 
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(MsBuildThisFileDirectory)\..\..\native\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <Link>\%(FileName)%(Extension)</Link>
    </None>
    <None Include="$(MsBuildThisFileDirectory)\..\..\native\mapnik\input\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>mapnik\input\%(FileName)%(Extension)</Link>
    </None>
    <None Include="$(MsBuildThisFileDirectory)\..\..\native\mapnik\fonts\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>mapnik\fonts\%(FileName)%(Extension)</Link>
    </None>
    <None Include="$(MsBuildThisFileDirectory)\..\..\native\share\gdal\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>share\gdal\%(FileName)%(Extension)</Link>
    </None>
    <None Include="$(MsBuildThisFileDirectory)\..\..\native\share\icu\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>share\icu\%(FileName)%(Extension)</Link>
    </None>
    <None Include="$(MsBuildThisFileDirectory)\..\..\native\share\proj\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>share\proj\%(FileName)%(Extension)</Link>
    </None>
  </ItemGroup>
</Project>

because the dlls in native file weren't copied and the other dlls were copied with an extra (.) between filename and extension. 

Could you plz help me?
PS. I am using VS2015 RTM, in a x64 platform and I switch the iisexpress into the x64 version.

**Comment by Charmatzis** [comment] 2015-08-27 15:15
The XML file mapnik.x64.props 
![mapnik x64 props](https://cloud.githubusercontent.com/assets/8981766/9524408/7f34b8f0-4ce7-11e5-9071-d9ee554fe9c6.png)
was rendered write so I have attached an image now....

**Comment by jskulavik** [comment] 2015-08-27 19:49
@Charmatzis: I encountered this early on too.  There are a bunch of reasons as to why this happens that @jbrwn could better explain, but you need to leverage the file system using Server.MapPath() such that Mapnik can find the missing directories.

**Comment by jbrwn** [comment] 2015-08-29 19:30
>I tried to do the same and install with a nuget package in an ASP.NET API project and and when I run the api site the error is:
"Could not load file or assembly 'NETMapnik.DLL' or one of its dependencies. The specified module could not be found" 

Your asp.net host is most likely using shadow copy.  This will copy all the .NET assemblies to a new directory but leave the native dlls in \bin.  A quick work around is to turn shadow copy off. This problem has been around for a while.  Here is a blog that explains the issue and offers a solution:

http://blogs.msdn.com/b/gduthie/archive/2006/11/09/tip-shadow-copy-and-your-bin-directory.aspx

>I also found that in the mapnik.x64.props file in packages there were some errors and you need to change it to that 

I'm not sure i am understanding what the issue is.  Can you please describe a step by step repro and/or submit a pull request with a fix?

**Comment by Charmatzis** [comment] 2015-08-30 14:36
You right the solution is to insert in web.config  `shadowCopyBinAssemblies="false"`
Here is the solution...

` <system.web>`
 ` <hostingEnvironment shadowCopyBinAssemblies="false" />`
`</system.web>`

THX!!!!
PS. I am new to git and I don't know how git works very well. I'll try to pull a request with some fixes.

**Comment by jbrwn** [comment] 2015-08-31 18:04
>THX!!!!
PS. I am new to git and I don't know how git works very well. I'll try to pull a request with some fixes.

No worries. I'm looking forward to your pull request.   I'm going to close this issue but please open a new one if you get stuck on anything else.

**Closed by jbrwn** 2015-08-31 18:04 UTC
